### ISSUE TITLE
运行前的准备工作

### ISSUE THREAD

**Issue by abstinentcode** [chenyx512/mit-primes#1]
你好，我想问一下，这个代码跑之前需要做什么准备呢？我安装好依赖以后直接运行train.py报错TypeError: __init__() got an unexpected keyword argument 'event_dir'，我感觉是使用数据集的问题，但是不知道该怎么修改，希望博主能简单解答一下训练前的准备工作，非常感谢！！！

**Comment by chenyx512** [comment]
微信yuxuanchen512

**Comment by chenyx512** [comment]
`event_dir` should be `event_path`, fixed and closing
